name: Deploy to Azure

on:
  workflow_run:
    workflows: ["Build and Push Docker Image"]
    types:
      - completed
    branches: [main]
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: ${{ secrets.AZURE_WEBAPP_NAME }}
  DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
  IMAGE_NAME: neonnovaapp

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    
    steps:
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
          images: ${{ env.DOCKER_HUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest
          startup-command: ''
          slot-name: production
          runtime-stack: DOCKER|latest
      
      - name: Log deployment status
        run: |
          echo "Deployed to ${{ secrets.AZURE_WEBAPP_NAME }} successfully"
          echo "Using image ${{ env.DOCKER_HUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest"